class AppText {
  static const List<String> categoryList = [
    'Electronics',
    'Clothing',
    'Bag',
    'Sports',
    'keys',
    'Kitchen',
    'Toys',
    'Games',
    'Books',
    'Medicine',
    'Jewelry',
    'Stationary',
    'Grocery',
    'Shoes',
    'Accessories',
    'Other',
  ];
  static const List<String> brandList = [
    'Apple',
    'Samsung',
    'Sony',
    'Dell',
    'HP',
    'LG',
    'Canon',
    'Panasonic',
    'Nike',
    'Adidas',
    'Gucci',
    'Zara',
    'H&M',
    'Levi\'s',
    'Tommy Hilfiger',
    'Ralph Lauren',
    'Calvin Klein',
    'Versace',
    'Bose',
    'Fitbit',
    'Louis Vuitton',
    'Coach',
    'Michael Kors',
    'Kate Spade',
    'Fossil',
    'Herschel',
    'Timbuk2',
    'Samsonite',
    'Tumi',
    'JanSport',
    'MAC Cosmetics',
    'Sephora',
    'NARS',
    'Maybelline',
    'Urban Decay',
    'Estée Lauder',
    'Too Faced',
    'Clinique',
    'Anastasia',
    'Fenty Beauty',
    'Chanel',
    'Prada',
    'Dior',
    'Balenciaga',
    'Alexander',
    'Valentino',
    'Gucci',
    'Burberry',
    'Fendi',
    'Yves Saint',
    'Other',
  ];
  static const List<String> colorList = [
    'Red',
    'Blue',
    'Green',
    'Yellow',
    'Orange',
    'Purple',
    'Pink',
    'Brown',
    'Black',
    'White',
    'Gray',
    'Sky Blue',
    'Beige',
    'Turquoise',
    'Lime',
    'Cyan',
    'Magenta',
    'Indigo',
    'Teal',
    'Lavender',
    'Maroon',
    'Olive',
    'Navy',
    'Silver',
    'Gold',
    'Other',
  ];
  static const String welcomeText =
      'Welcome to Finder App, your trusted companion in locating lost items.';
  static const String registerText =
      'Enter essential details below to register and amplify your presence on Finder.';
}
